const games_data =  [
                        ['user1',  'user1@mail.com',  '15.06.2022 15:48', 'Wygrana'  ],
                        ['user2',  'user2@mail.com',  '15.06.2022 15:48', 'Wygrana'  ],
                        ['user3',  'user3@mail.com',  '15.06.2022 15:48', 'Przegrana'],
                        ['user4',  'user4@mail.com',  '15.06.2022 15:48', 'Wygrana'  ],
                        ['user5',  'user5@mail.com',  '15.06.2022 15:48', 'Przegrana'],
                        ['user6',  'user6@mail.com',  '15.06.2022 15:48', 'Wygrana'  ],
                        ['user7',  'user7@mail.com',  '15.06.2022 15:48', 'Wygrana'  ],
                        ['user8',  'user8@mail.com',  '15.06.2022 15:48', 'Wygrana'  ],
                        ['user9',  'user9@mail.com',  '15.06.2022 15:48', 'Przegrana'],
                        ['user10', 'user10@mail.com', '15.06.2022 15:48', 'Wygrana'  ],
                        ['user11', 'user11@mail.com', '15.06.2022 15:48', 'Wygrana'  ],
                        ['user12', 'user12@mail.com', '15.06.2022 15:48', 'Przegrana'],
                        ['user13', 'user13@mail.com', '15.06.2022 15:48', 'Przegrana'],
                        ['user14', 'user14@mail.com', '15.06.2022 15:48', 'Przegrana'],
                        ['user15', 'user15@mail.com', '15.06.2022 15:48', 'Wygrana'  ],
                    ];


const users_data =  [
                        ['user1',  'user1@mail.com',  true],
                        ['user2',  'user2@mail.com',  false],
                        ['user3',  'user3@mail.com',  false],
                        ['user4',  'user4@mail.com',  false],
                        ['user5',  'user5@mail.com',  true],
                        ['user6',  'user6@mail.com',  false],
                        ['user7',  'user7@mail.com',  true],
                        ['user8',  'user8@mail.com',  false],
                        ['user9',  'user9@mail.com',  false],
                        ['user10', 'user10@mail.com', false],
                        ['user11', 'user11@mail.com', false],
                        ['user12', 'user12@mail.com', false],
                        ['user13', 'user13@mail.com', false],
                        ['user14', 'user14@mail.com', false],
                        ['user15', 'user15@mail.com', false],
                        ['user16', 'user16@mail.com', false],
                        ['user17', 'user17@mail.com', true],
                    ];


const friends_data = [
                        ['user1', 'user1@mail.com',   'Online' ],
                        ['user2',  'user2@mail.com',  'Online' ],
                        ['user3',  'user3@mail.com',  'Offline'],
                        ['user4',  'user4@mail.com',  'Online' ],
                        ['user5',  'user5@mail.com',  'Offline'],
                        ['user6',  'user6@mail.com',  'Offline'],
                        ['user7',  'user7@mail.com',  'Online' ],
                        ['user8',  'user8@mail.com',  'Online' ],
                        ['user9',  'user9@mail.com',  'Offline'],
                        ['user10', 'user10@mail.com', 'Online' ],
                        ['user11', 'user11@mail.com', 'Offline'],
                        ['user12', 'user12@mail.com', 'Offline'],
                        ['user13', 'user13@mail.com', 'Offline'],
                        ['user14', 'user14@mail.com', 'Online' ],
                        ['user15', 'user15@mail.com', 'Online' ],
                        ['user16', 'user16@mail.com', 'Online' ],
                        ['user17', 'user17@mail.com', 'Offline'],
                        ['user18', 'user18@mail.com', 'Offline'],
                        ['user19', 'user19@mail.com', 'Offline'],
                        ['user20', 'user20@mail.com', 'Online' ],
                        ['user21', 'user21@mail.com', 'Offline'],
                        ['user22', 'user22@mail.com', 'Online' ],
                        ['user23', 'user23@mail.com', 'Offline'],
                    ];

export { friends_data, users_data, games_data };